"""ajustando a tabela de CAlclation de forma certa

Revision ID: 379228dfadf1
Revises: ee3b2d0033af
Create Date: 2025-10-15 19:35:14.548287

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '379228dfadf1'
down_revision: Union[str, Sequence[str], None] = 'ee3b2d0033af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
