"""ajustando a tabela de calculation da forma certa

Revision ID: 8da4b203b673
Revises: 379228dfadf1
Create Date: 2025-10-15 22:22:44.241975

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '8da4b203b673'
down_revision: Union[str, Sequence[str], None] = '379228dfadf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
